### ISSUE TITLE
RUNNING THE CODE!!

### ISSUE THREAD

**Issue by marinabosque** [dgentil1/Katrina#21]
Guys in the dofile "S_SCM_asec.do" at the very beginning of the file instead of:

 
 *------------------------- Synthetic Control Method --------------------------*
  ***** Define Program 
program s_scm

should be:

 
 *------------------------- Synthetic Control Method --------------------------*
  ***** Define Program 
program s_scm_asec

otherwise the whole program does not work...

Can I change it in the master?

**Comment by dgentil1** [comment]
Please don't! 

I have done a lot of changes yesterday, in particular this one but I forgot to commit! I will update the master as soon as I get to my office.

**Comment by marinabosque** [comment]
OKEY! That is why I ask first jejeje

Btw, you can get rid of the cap saveold command! It works!

**Comment by dgentil1** [comment]
Go ahead and remove them if you don;t need them anymore.
