### ISSUE TITLE
Create two treatment groups

### ISSUE THREAD

**Issue by marinabosque** [dgentil1/Katrina#7]
Create two samples:

1) Assignment to treatment group -> 0.5 upper threshold

1) Assignment to treatment group -> 0.3/0.2 upper threshold --> More MSAs, restrict it to at least 100 obs.

**Comment by dgentil1** [comment]
This task is completed. Finally I used an upper_threshold of 0.5 for treat and one of 0.1 for treat_expanded.

in treat_expanded we have 9 cities (including the 3 we had before) and the point estimate for the share of evacuees range from 0.65% to 2.2% so it looks good! We also have some medium big cities like Memphis or Las Vegas!
