### ISSUE TITLE
Short and Long Term DiD

### ISSUE THREAD

**Issue by marinabosque** [dgentil1/Katrina#9]
Create both a long and short term pre and post trends for the DiD.

Try Time span --> 1999-2011

**Comment by dgentil1** [comment]
Reassigning this to Mar!

**Comment by dgentil1** [comment]
Reassigning this to me

**Comment by dgentil1** [comment]
This task is complete now. For computing the diff in diff estimates and for showing the pretrends just years from 1999 to 2011 are used.
